### ISSUE TITLE
I want to create view something like this

### ISSUE THREAD

**Issue by chnouman** [diogobernardino/RossDeckView#9]
if you have any suggestion and library reference them please share.

**Comment by chnouman** [comment]
![20170920_083843](https://user-images.githubusercontent.com/15146352/30729559-567afe56-9f15-11e7-8419-6cd38f9ffa15.jpg)

**Comment by chnouman** [comment]
![20170920_083843](https://user-images.githubusercontent.com/15146352/30729559-567afe56-9f15-11e7-8419-6cd38f9ffa15.jpg)

**Comment by diogobernardino** [comment]
You won't be able to achieve that with this library.

**Comment by chnouman** [comment]
ok dear thanks

**Comment by navneet93sharma** [comment]
@chnouman do you have any solution now for this?

**Comment by chnouman** [comment]
not exactly but i got some alternatives by the way https://android-arsenal.com/details/1/4025
and https://android-arsenal.com/tag/198?category=1
